import mongoose from 'mongoose'
import bcrypt from 'bcryptjs'

const { Schema } = mongoose

const EmployeeSchema = new Schema(
  {
    employeeNumber: { type: String, required: true, unique: true, trim: true },

    // Identity
    firstName: { type: String, required: true, trim: true },
    middleName: { type: String, trim: true, default: '' },
    lastName: { type: String, required: true, trim: true },
    suffix: { type: String, trim: true, default: '' },

    // Login credentials (employees and admins both log in)
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    passwordHash: { type: String, required: true },
    role: { type: String, enum: ['super_admin', 'admin', 'employee'], default: 'employee' },

    // Contact
    phone: { type: String, trim: true, default: '' },
    address: { type: String, trim: true, default: '' },

    // Employment details
    department: { type: String, trim: true, default: '' },
    position: { type: String, trim: true, default: '' },
    employmentType: {
      type: String,
      enum: ['regular', 'probationary', 'contractual', 'project-based'],
      default: 'regular'
    },
    dateHired: { type: Date, required: true },
    dateSeparated: { type: Date, default: null },
    status: { type: String, enum: ['active', 'inactive', 'separated'], default: 'active' },

    // Compensation
    basicSalary: { type: Number, required: true, min: 0 }, // monthly basic salary, PHP
    payFrequency: { type: String, enum: ['monthly', 'semi-monthly'], default: 'semi-monthly' },
    allowances: {
      deMinimis: { type: Number, default: 0 }, // non-taxable allowance per month (PHP), e.g. rice/meal/transpo within BIR limits
      taxableAllowance: { type: Number, default: 0 } // any other regular taxable allowance per month
    },
    bankAccount: {
      bankName: { type: String, trim: true, default: '' },
      accountNumber: { type: String, trim: true, default: '' }
    },

    // Government-mandated IDs
    governmentIds: {
      sssNumber: { type: String, trim: true, default: '' },
      philhealthNumber: { type: String, trim: true, default: '' },
      pagibigNumber: { type: String, trim: true, default: '' },
      tin: { type: String, trim: true, default: '' }
    },

    // Tax status — affects nothing under TRAIN law directly (no more additional exemptions)
    // but kept for recordkeeping / BIR Form 2316 purposes
    taxStatus: { type: String, default: 'Single' },

    // Leave credits (simple balance model)
    leaveCredits: {
      vacation: { type: Number, default: 15 },
      sick: { type: Number, default: 15 }
    },

    // Per-employee custom deductions on top of statutory SSS/PhilHealth/Pag-IBIG/
    // BIR amounts — e.g. loan repayments, cash advances, uniform fees. Each item
    // can combine a percentage of basic salary AND/OR a fixed peso amount; both
    // apply together if both are set (e.g. 5% + ₱200 fixed in the same item).
    // Percentage is always computed off basic salary, then prorated by pay
    // frequency the same way statutory contributions are (see payrollEngine.js).
    customDeductions: [
      {
        label: { type: String, required: true, trim: true }, // e.g. "Company Loan", "Uniform Fee"
        percentage: { type: Number, default: 0, min: 0, max: 100 }, // % of monthly basic salary
        fixedAmount: { type: Number, default: 0, min: 0 }, // flat ₱ amount per month
        active: { type: Boolean, default: true },
        notes: { type: String, trim: true, default: '' }
      }
    ],

    mustChangePassword: { type: Boolean, default: true },

    // Short numeric PIN used ONLY at the DTR kiosk — see dtrPinHash above.
    dtrPinHash: { type: String, default: null },

    // Barcode and NFC credential hashes for the DTR kiosk. The raw barcode
    // value or NFC UID is hashed before storage — the actual card/fob ID is
    // never stored in plaintext. Both are optional; employees can use PIN
    // only, barcode only, NFC only, or any combination. Only a super_admin
    // can assign these from Settings — employees cannot set them themselves.
    dtrBarcodeHash: { type: String, default: null },
    dtrNfcHash: { type: String, default: null },

    // QR code credential for the DTR kiosk. Unlike barcode/NFC (where the
    // value comes from external hardware and is only ever hashed), this QR
    // value is GENERATED by the system itself — so it needs to be retrievable
    // to redisplay/reprint the badge later, not just hashed. dtrQrHash is
    // still what the kiosk actually compares against on scan (consistent with
    // barcode/NFC); dtrQrValue is kept so Super Admin can view/reprint it
    // without needing to regenerate a new code each time.
    dtrQrValue: { type: String, default: null },
    dtrQrHash: { type: String, default: null }
  },
  { timestamps: true }
)

EmployeeSchema.virtual('fullName').get(function () {
  const parts = [this.firstName, this.middleName, this.lastName, this.suffix].filter(Boolean)
  return parts.join(' ')
})

EmployeeSchema.set('toJSON', {
  virtuals: true,
  transform(_doc, ret) {
    delete ret.passwordHash
    delete ret.dtrPinHash
    delete ret.dtrBarcodeHash
    delete ret.dtrNfcHash
    delete ret.dtrQrValue
    delete ret.dtrQrHash
    return ret
  }
})

EmployeeSchema.methods.comparePassword = function (candidate) {
  return bcrypt.compare(candidate, this.passwordHash)
}

EmployeeSchema.methods.compareDtrPin = function (candidate) {
  if (!this.dtrPinHash) return Promise.resolve(false)
  return bcrypt.compare(candidate, this.dtrPinHash)
}

EmployeeSchema.methods.compareDtrBarcode = function (candidate) {
  if (!this.dtrBarcodeHash) return Promise.resolve(false)
  return bcrypt.compare(candidate, this.dtrBarcodeHash)
}

EmployeeSchema.methods.compareDtrNfc = function (candidate) {
  if (!this.dtrNfcHash) return Promise.resolve(false)
  return bcrypt.compare(candidate, this.dtrNfcHash)
}

EmployeeSchema.statics.hashPassword = function (plain) {
  return bcrypt.hash(plain, 10)
}

EmployeeSchema.statics.hashDtrPin = function (plain) {
  return bcrypt.hash(plain, 10)
}

export default mongoose.models.Employee || mongoose.model('Employee', EmployeeSchema)
