import mongoose from 'mongoose'

const { Schema } = mongoose

// One PayrollRecord = one employee's payslip for one cutoff period.
// Generated by the payroll engine (server/utils/payrollEngine.js) and stored
// so history/reports can be queried without recomputation.
const PayrollRecordSchema = new Schema(
  {
    employee: { type: Schema.Types.ObjectId, ref: 'Employee', required: true },

    // Identifies the pay run this record belongs to
    periodStart: { type: Date, required: true },
    periodEnd: { type: Date, required: true },
    payDate: { type: Date, required: true },
    cutoff: { type: String, enum: ['1st', '2nd', 'monthly'], required: true },
    runLabel: { type: String, required: true }, // e.g. "June 2026 - 2nd Cutoff"

    // Snapshot of inputs used (so historical payslips stay accurate even if
    // the employee's salary changes later)
    basicSalarySnapshot: { type: Number, required: true },

    // Daily/hourly rate used for each calendar month the cutoff touches:
    // monthly salary ÷ number of Mon–Sat days in that month.
    rateBasis: [
      {
        month: { type: String }, // 'YYYY-MM'
        workingDays: { type: Number, default: 0 },
        dailyRate: { type: Number, default: 0 },
        hourlyRate: { type: Number, default: 0 }
      }
    ],

    // Whether each statutory deduction was computed for this run. Each defaults
    // true (the only behavior before this flag existed). An admin can uncheck
    // any one independently — e.g. exclude SSS but keep withholding tax. Kept
    // on the record itself, not just implied by zero deduction values, so the
    // payslip can clearly say which were excluded rather than looking like an error.
    governmentDeductionsIncluded: {
      sss: { type: Boolean, default: true },
      philHealth: { type: Boolean, default: true },
      pagIbig: { type: Boolean, default: true },
      withholdingTax: { type: Boolean, default: true }
    },

    attendanceSummary: {
      scheduledDays: { type: Number, default: 0 }, // Mon–Sat days in the cutoff
      daysWorked: { type: Number, default: 0 },
      absences: { type: Number, default: 0 },
      noWorkDays: { type: Number, default: 0 },
      lateMinutes: { type: Number, default: 0 },
      undertimeMinutes: { type: Number, default: 0 },
      overtimeHours: { type: Number, default: 0 }, // total OT hours across all day types, kept for backward compatibility
      halfDayHoursShort: { type: Number, default: 0 },
      ordinaryOvertimeHours: { type: Number, default: 0 },
      restDayHoursWorked: { type: Number, default: 0 },
      restDayOvertimeHours: { type: Number, default: 0 },
      specialDayHoursWorked: { type: Number, default: 0 },
      specialDayOvertimeHours: { type: Number, default: 0 },
      holidayHoursWorked: { type: Number, default: 0 },
      holidayOvertimeHours: { type: Number, default: 0 },
      leaveDaysPaid: { type: Number, default: 0 },
      leaveDaysUnpaid: { type: Number, default: 0 }
    },

    // Day-by-day computation trail shown on the payslip's detailed breakdown —
    // one line per attendance record (plus one summary line for unrecorded
    // days), explaining exactly which formula was applied and the resulting
    // peso amount. Persisted (not recomputed on view) so a finalized/paid
    // payslip's explanation stays accurate even if attendance data changes later.
    dailyBreakdown: [
      {
        date: { type: Date, default: null }, // null for the monthly rounding line
        status: { type: String },
        dayLabel: { type: String, default: '' }, // e.g. "Regular Holiday on Rest Day"
        hoursWorked: { type: Number, default: 0 },
        overtimeHours: { type: Number, default: 0 },
        lateMinutes: { type: Number, default: 0 },
        undertimeMinutes: { type: Number, default: 0 },
        amount: { type: Number, default: 0 }, // net pay impact for that line (+earned / -deducted)
        formula: { type: String, default: '' }
      }
    ],

    earnings: {
      basicPay: { type: Number, default: 0 },
      overtimePay: { type: Number, default: 0 }, // total of all OT premiums below, for backward compatibility
      overtimeBreakdown: {
        ordinaryOvertimePay: { type: Number, default: 0 },
        restDayOvertimePay: { type: Number, default: 0 },
        specialDayOvertimePay: { type: Number, default: 0 },
        holidayOvertimePay: { type: Number, default: 0 }
      },
      premiumPay: { type: Number, default: 0 }, // "first 8 hours" premium for rest day / special day / holiday worked
      premiumBreakdown: {
        restDayPay: { type: Number, default: 0 },
        specialDayPay: { type: Number, default: 0 },
        holidayPay: { type: Number, default: 0 }
      },
      allowances: { type: Number, default: 0 }, // taxable allowance portion for the period
      deMinimis: { type: Number, default: 0 }, // non-taxable allowance portion for the period
      thirteenthMonthPay: { type: Number, default: 0 },
      otherEarnings: { type: Number, default: 0 },
      grossPay: { type: Number, default: 0 }
    },

    // Employee-specific reimbursements added at generation time (e.g. transportation,
    // client meals, supplies). Non-taxable and excluded from grossPay and all
    // statutory contribution bases — added straight onto netPay instead.
    reimbursements: [
      {
        description: { type: String, trim: true, required: true },
        amount: { type: Number, required: true, min: 0 }
      }
    ],
    totalReimbursements: { type: Number, default: 0 },

    // A single flat, labeled, ad-hoc deduction picked at generation time (e.g.
    // a one-off shared expense), applied identically to every employee in the
    // run. Stored separately from deductions.otherDeductions (which internally
    // combines this amount with itemized customDeductionsApplied) so the
    // payslip can always show this specific labeled line on its own.
    otherDeductionDescription: { type: String, trim: true, default: '' },
    otherDeductionAmount: { type: Number, default: 0 },

    deductions: {
      sssEmployee: { type: Number, default: 0 },
      philhealthEmployee: { type: Number, default: 0 },
      pagibigEmployee: { type: Number, default: 0 },
      withholdingTax: { type: Number, default: 0 },
      lateUndertimeDeduction: { type: Number, default: 0 },
      absenceDeduction: { type: Number, default: 0 },
      noWorkDeduction: { type: Number, default: 0 },
      halfDayDeduction: { type: Number, default: 0 },
      otherDeductions: { type: Number, default: 0 }, // sum of customDeductionsApplied below, for backward compatibility
      customDeductionsApplied: [
        {
          label: { type: String },
          percentage: { type: Number, default: 0 },
          fixedAmount: { type: Number, default: 0 },
          amount: { type: Number, default: 0 } // computed total for this item this period
        }
      ],
      totalDeductions: { type: Number, default: 0 }
    },

    employerContributions: {
      sssEmployer: { type: Number, default: 0 },
      philhealthEmployer: { type: Number, default: 0 },
      pagibigEmployer: { type: Number, default: 0 },
      ecContribution: { type: Number, default: 0 }
    },

    netPay: { type: Number, required: true },

    status: { type: String, enum: ['draft', 'finalized', 'paid', 'cancelled'], default: 'draft' },
    generatedBy: { type: Schema.Types.ObjectId, ref: 'Employee' },

    // Audit trail for cancellation — record is never deleted once finalized/paid,
    // only marked cancelled, so history stays intact and explainable.
    cancelledAt: { type: Date, default: null },
    cancelledBy: { type: Schema.Types.ObjectId, ref: 'Employee', default: null },
    cancellationReason: { type: String, trim: true, default: '' },
    statusBeforeCancellation: { type: String, enum: ['draft', 'finalized', 'paid', null], default: null }
  },
  { timestamps: true }
)

PayrollRecordSchema.index({ employee: 1, periodStart: 1, periodEnd: 1 }, { unique: true })

export default mongoose.models.PayrollRecord || mongoose.model('PayrollRecord', PayrollRecordSchema)
